Improve the typing of the Strategy class hierarchy.
node-saml/passport-saml pull request #554
Opened 2021-03-15 22:51 UTC by forty

# Description

The goal of this PR is to improve the typing of the Strategy class hierarchy.

The current expected ts error causes problems with some earlier version of TS. 
```
[watch:ts] node_modules/passport-saml/lib/passport-saml/multiSamlStrategy.d.ts(10,5): error TS2416: Property 'generateServiceProviderMetadata' in type 'MultiSamlStrategy' is not assignable to the same property in base type 'Strategy'.
[watch:ts]   Type '(req: Request, decryptionCert: string, signingCert: string, callback: (err: Error, metadata?: string) => void) => void' is not assignable to type '(decryptionCert: string, signingCert?: string) => string'.
```
See https://github.com/node-saml/passport-saml/issues/540 which seems to be affected by this too.

Also, it does not make any sense to have a method override a method with a different signature, just because they have the same name.

2021-03-16 00:04 UTC, cjbarth commented
This looks good to me. I have a significant refactor of the type system in #548 which addresses some complex issues surrounding requiring a cert. I'm trying to get that landed before changes like this; though we'll certainly get this landed before we release v3. Feel free to have a look at it and offer feedback.

2021-03-18 14:10 UTC, cjbarth commented
Is this something that you wanted fixed in the 2.x branch, or just in `master`?

2021-03-18 14:42 UTC, forty commented
@cjbarth I'm actually mostly interested by the 2.x branch for now, since that's what I'm using at the moment. I'll open a PR for that branch too :+1:

2021-03-19 13:48 UTC, cjbarth commented
@forty Would you like to resolve the merge conflicts so we can get this landed as part of the upcoming 3.x release?

2021-03-22 10:32 UTC, forty commented
Just rebased on master :+1:

2021-03-22 15:59 UTC, cjbarth requested changes
As we go along, I'm OK with adding types and making other minor changes in files we're touching to reduce the number of `eslint` errors.

2021-03-22 15:59 UTC, cjbarth commented on test/multiSamlStrategy.spec.ts
> +      .stub(AbstractStrategy.prototype as any, "_generateServiceProviderMetadata") // force type to any to ignore TS protected property
Why not get rid of `any` and stub `SAML.generateServiceProviderMetadata` instead?

2021-03-22 15:59 UTC, cjbarth commented on test/multiSamlStrategy.spec.ts
> +    strategy.should.be.an.instanceOf(AbstractStrategy);
We should probably include another assert to make sure that it also extends `PassportStrategy`, just to make it clear the chain goes back to something that works with Passport.

2021-04-05 17:43 UTC, cjbarth commented
@forty Would you like to get this rebased and we'll get it landed? If you need help, please let me know.

2021-04-05 19:40 UTC, forty commented
@cjbarth I just rebased on latest master :+1:

2021-04-05 19:55 UTC, cjbarth approved these changes

2021-04-05 19:56 UTC, merged

2021-04-05 19:56 UTC, cjbarth commented
If you want this on 2.x, please create a PR there.