resolve XML-encoded carriage returns during signature validation
node-saml/passport-saml pull request #576
Opened 2021-03-25 18:09 UTC by mhassan1

# Description

Resolves https://github.com/node-saml/passport-saml/issues/575. See that issue for background.

This adds XML normalization to `validateSignatureForCert` before sending it to `xml-crypto`. It uses `DOMParser` for normalization tasks such as replacement of XML-encoded entities (`&#13;`) with their actual representations (carriage return).

# Checklist:

- Issue Addressed: [X]
- Link to SAML spec: [ ]
- Tests included? [X]
- Documentation updated? N/A

2021-03-25 18:31 UTC, markstos commented
I reviewed the diff, LGTM.

2021-03-25 18:32 UTC, markstos approved these changes

2021-03-25 18:32 UTC, markstos commented
Thanks for including some tests.

2021-03-25 18:32 UTC, markstos commented
@cjbarth This seems like a fix worth releasing on the 2.x branch.

2021-03-26 21:55 UTC, cjbarth commented
I will gladly release 2.x if another PR against that branch is landed. As for this, I'd like to let #574 land before landing this so that we don't cause merge conflicts for that huge PR. We'll still get this landed before 3.x.

@mhassan1, would you like to create this PR against the 2.x branch so we can do a release to the 2.x series while we are waiting for 3.x to get finished up?

2021-03-29 02:25 UTC, mhassan1 commented
@cjbarth PR for 2.x: https://github.com/node-saml/passport-saml/pull/578

2021-04-05 17:47 UTC, cjbarth commented
@mhassan1 Could you please update this PR to resolve the merge conflicts and we'll get this landed for the 3.x release?

2021-04-05 18:36 UTC, cjbarth requested changes

2021-04-05 18:36 UTC, cjbarth commented on test/node-saml/test-signatures.spec.ts
> +        __dirname + "/static/signatures/valid/response.root-unsigned.assertion-signed.xml"
I think this path has changed.

2021-04-05 19:52 UTC, merged